require("config.options")
require("config.quickfix")
require("config.clipboard")
require("config.lazy")
require("config.user_commands")
require("config.autocmds")
require("config.keymaps")
require("config.lsp")
